/* **************************************************************************** */
/*																				*/
/* Caml Bindings for Input Devices												*/
/*		(c)2002 Motion-Twin														*/
/*																				*/
/* **************************************************************************** */
#pragma once

#define DIRECTINPUT_VERSION 0x0800
#define DI_BUFFERSIZE		32
#include <dinput.h>

typedef struct {
	int code;
	const char *name;
} key;


const key allkeys[] = {

{DIK_ESCAPE         ,"Esc"},
{DIK_1              ,"1"},
{DIK_2              ,"2"},
{DIK_3              ,"3"},
{DIK_4              ,"4"},
{DIK_5              ,"5"},
{DIK_6              ,"6"},
{DIK_7              ,"7"},
{DIK_8              ,"8"},
{DIK_9              ,"9"},
{DIK_0              ,"0"},
{DIK_MINUS          ,"-"},
{DIK_EQUALS         ,"="},
{DIK_BACK           ,"Backspace"},
{DIK_TAB            ,"Tab"},
{DIK_Q              ,"Q"},
{DIK_W              ,"W"},
{DIK_E              ,"E"},
{DIK_R              ,"R"},
{DIK_T              ,"T"},
{DIK_Y              ,"Y"},
{DIK_U              ,"U"},
{DIK_I              ,"I"},
{DIK_O              ,"O"},
{DIK_P              ,"P"},
{DIK_LBRACKET       ,"["},
{DIK_RBRACKET       ,"]	"},
{DIK_RETURN         ,"Return"},
{DIK_LCONTROL       ,"LCtrl"},
{DIK_A              ,"A"},
{DIK_S              ,"S"},
{DIK_D              ,"D"},
{DIK_F              ,"F"},
{DIK_G              ,"G"},
{DIK_H              ,"H"},
{DIK_J              ,"J"},
{DIK_K              ,"K"},
{DIK_L              ,"L"},
{DIK_SEMICOLON      ,";"},
{DIK_APOSTROPHE     ,"'"},
{DIK_GRAVE          ,"~"},
{DIK_LSHIFT         ,"LShift"},
{DIK_BACKSLASH      ,"\\"},
{DIK_Z              ,"Z"},
{DIK_X              ,"X"},
{DIK_C              ,"C"},
{DIK_V              ,"V"},
{DIK_B              ,"B"},
{DIK_N              ,"N"},
{DIK_M              ,"M"},
{DIK_COMMA          ,","},
{DIK_PERIOD         ,"."},
{DIK_SLASH          ,"/"},
{DIK_RSHIFT         ,"RShift"},
{DIK_MULTIPLY       ,"*"},
{DIK_LMENU          ,"LAlt"},
{DIK_SPACE          ,"Space"},
{DIK_CAPITAL        ,"Caps"},
{DIK_F1             ,"F1"},
{DIK_F2             ,"F2"},
{DIK_F3             ,"F3"},
{DIK_F4             ,"F4"},
{DIK_F5             ,"F5"},
{DIK_F6             ,"F6"},
{DIK_F7             ,"F7"},
{DIK_F8             ,"F8"},
{DIK_F9             ,"F9"},
{DIK_F10            ,"F10"},
{DIK_NUMLOCK        ,"NumLock"},
{DIK_SCROLL         ,"Scroll"},
{DIK_NUMPAD7        ,"Num7"},
{DIK_NUMPAD8        ,"Num8"},
{DIK_NUMPAD9        ,"Num9"},
{DIK_SUBTRACT       ,"Minus"},
{DIK_NUMPAD4        ,"Num4"},
{DIK_NUMPAD5        ,"Num5"},
{DIK_NUMPAD6        ,"Num6"},
{DIK_ADD            ,"Add"},
{DIK_NUMPAD1        ,"Num1"},
{DIK_NUMPAD2        ,"Num2"},
{DIK_NUMPAD3        ,"Num3"},
{DIK_NUMPAD0        ,"Num0"},
{DIK_DECIMAL        ,"Decimal"},
{DIK_OEM_102        ,"<"},
{DIK_F11            ,"F11"},
{DIK_F12            ,"F12"},
{DIK_F13            ,"F13"},
{DIK_F14            ,"F14"},
{DIK_F15            ,"F15"},
{DIK_KANA           ,"Kana"},
{DIK_ABNT_C1        ,"?"},
{DIK_CONVERT        ,"Conv"},
{DIK_NOCONVERT      ,"NoConv"},
{DIK_YEN            ,"Yen"},
{DIK_ABNT_C2        ,"Decimal"},
{DIK_NUMPADEQUALS   ,"Equal"},
{DIK_PREVTRACK      ,"Prev"},
{DIK_AT             ,"@"},
{DIK_COLON          ,"|"},
{DIK_UNDERLINE      ,"_"},
{DIK_KANJI          ,"Kanji"},
{DIK_STOP           ,"Stop"},
{DIK_AX             ,"AX"},
{DIK_UNLABELED      ,"Unknown"},
{DIK_NEXTTRACK      ,"Next"},
{DIK_NUMPADENTER    ,"Enter"},
{DIK_RCONTROL       ,"RCtrl"},
{DIK_MUTE           ,"Mute"},
{DIK_CALCULATOR     ,"Calc"},
{DIK_PLAYPAUSE      ,"Play"},
{DIK_MEDIASTOP      ,"Media"},
{DIK_VOLUMEDOWN     ,"VolumeDown"},
{DIK_VOLUMEUP       ,"VolumeUp"},
{DIK_WEBHOME        ,"Web"},
{DIK_NUMPADCOMMA    ,"Comma"},
{DIK_DIVIDE         ,"Div"},
{DIK_SYSRQ          ,"System"},
{DIK_RMENU          ,"RAlt"},
{DIK_PAUSE          ,"Pause"},
{DIK_HOME           ,"Home"},
{DIK_UP             ,"Up"},
{DIK_PRIOR          ,"PgUp"},
{DIK_LEFT           ,"Left"},
{DIK_RIGHT          ,"Right"},
{DIK_END            ,"End"},
{DIK_DOWN           ,"Down"},
{DIK_NEXT           ,"PgDown"},
{DIK_INSERT         ,"Ins"},
{DIK_DELETE         ,"Del"},
{DIK_LWIN           ,"LWin"},
{DIK_RWIN           ,"RWin"},
{DIK_APPS           ,"App"},
{DIK_POWER          ,"Power"},
{DIK_SLEEP          ,"Sleep"},
{DIK_WAKE           ,"Wake"},
{DIK_WEBSEARCH      ,"Search"},
{DIK_WEBFAVORITES   ,"Favorites"},
{DIK_WEBREFRESH     ,"Refresh"},
{DIK_WEBSTOP        ,"Stop"},
{DIK_WEBFORWARD     ,"Forward"},
{DIK_WEBBACK        ,"Previous"},
{DIK_MYCOMPUTER     ,"Computer"},
{DIK_MAIL           ,"Mail"},
{DIK_MEDIASELECT    ,"MediaSelect"}

};

#define ALLKEYSIZE (sizeof(allkeys)/sizeof(key))

/* **************************************************************************** */
