(* GENERATED BY SYMBOLS-plugin for Dragoon3 *)

let safe_cast x = (Obj.magic x : Vfs.fid)

let fBoardModel = safe_cast (-12)
let fCardBackGround = safe_cast (-7)
let fCardHiddenFace = safe_cast (-18)
let fEventArt_Draw = safe_cast (-20)
let fEventArt_Invoke = safe_cast (-21)
let fMouseCursors = safe_cast (-10)
let fSelCursorAttack = safe_cast (-32)
let fSelCursorInvoke = safe_cast (-31)
let fSelCursorMove = safe_cast (-33)
let fSelectionModel = safe_cast (-14)
